/* Code generated by cmd/cgo; DO NOT EDIT. */

/* package microscript_http */


#line 1 "cgo-builtin-export-prolog"

#include <stddef.h>

#ifndef GO_CGO_EXPORT_PROLOGUE_H
#define GO_CGO_EXPORT_PROLOGUE_H

#ifndef GO_CGO_GOSTRING_TYPEDEF
typedef struct { const char *p; ptrdiff_t n; } _GoString_;
#endif

#endif

/* Start of preamble from import "C" comments.  */




/* End of preamble from import "C" comments.  */


/* Start of boilerplate cgo prologue.  */
#line 1 "cgo-gcc-export-header-prolog"

#ifndef GO_CGO_PROLOGUE_H
#define GO_CGO_PROLOGUE_H

typedef signed char GoInt8;
typedef unsigned char GoUint8;
typedef short GoInt16;
typedef unsigned short GoUint16;
typedef int GoInt32;
typedef unsigned int GoUint32;
typedef long long GoInt64;
typedef unsigned long long GoUint64;
typedef GoInt64 GoInt;
typedef GoUint64 GoUint;
typedef size_t GoUintptr;
typedef float GoFloat32;
typedef double GoFloat64;
#ifdef _MSC_VER
#include <complex.h>
typedef _Fcomplex GoComplex64;
typedef _Dcomplex GoComplex128;
#else
typedef float _Complex GoComplex64;
typedef double _Complex GoComplex128;
#endif

/*
  static assertion to make sure the file is being used on architecture
  at least with matching size of GoInt.
*/
typedef char _check_for_64_bit_pointer_matching_GoInt[sizeof(void*)==64/8 ? 1:-1];

#ifndef GO_CGO_GOSTRING_TYPEDEF
typedef _GoString_ GoString;
#endif
typedef void *GoMap;
typedef void *GoChan;
typedef struct { void *t; void *v; } GoInterface;
typedef struct { void *data; GoInt len; GoInt cap; } GoSlice;

#endif

/* End of boilerplate cgo prologue.  */

#ifdef __cplusplus
extern "C" {
#endif

extern __declspec(dllexport) GoInt createServer(GoInt port);
extern __declspec(dllexport) void stopServer(GoInt serverHandle);
extern __declspec(dllexport) GoUint8 isRunning(GoInt serverHandle);

// Route handling
//
extern __declspec(dllexport) void addRoute(GoInt serverHandle, char* method, char* path, char* handlerName);
extern __declspec(dllexport) void removeRoute(GoInt serverHandle, char* method, char* path);

// Response utilities
//
extern __declspec(dllexport) void setResponseHeader(GoInt requestId, char* name, char* value);
extern __declspec(dllexport) void sendResponse(GoInt requestId, GoInt statusCode, char* contentType, char* body);
extern __declspec(dllexport) void sendJsonResponse(GoInt requestId, GoInt statusCode, char* jsonBody);
extern __declspec(dllexport) void sendFileResponse(GoInt requestId, char* filePath);

// Request information
//
extern __declspec(dllexport) char* getRequestPath(GoInt requestId);
extern __declspec(dllexport) char* getRequestMethod(GoInt requestId);
extern __declspec(dllexport) char* getRequestHeader(GoInt requestId, char* headerName);
extern __declspec(dllexport) char* getRequestBody(GoInt requestId);
extern __declspec(dllexport) char* getQueryParam(GoInt requestId, char* paramName);

// Middleware
//
extern __declspec(dllexport) void useMiddleware(GoInt serverHandle, char* middlewareName);

// Utility functions
//
extern __declspec(dllexport) char* urlEncode(char* input);
extern __declspec(dllexport) char* urlDecode(char* input);
extern __declspec(dllexport) char* generateUuid();
extern __declspec(dllexport) GoInt createWebSocketEndpoint(GoInt serverHandle, char* path);
extern __declspec(dllexport) void sendWebSocketMessage(GoInt endpointHandle, char* clientId, char* message);
extern __declspec(dllexport) void broadcastWebSocketMessage(GoInt endpointHandle, char* message);
extern __declspec(dllexport) void closeWebSocketConnection(GoInt endpointHandle, char* clientId);

#ifdef __cplusplus
}
#endif
